"""Initial migration 2

Revision ID: ecf7eb77cb27
Revises: ee6bc7f24531
Create Date: 2023-05-27 20:02:30.758106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecf7eb77cb27'
down_revision = 'ee6bc7f24531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
