"""Descripción de la migración

Revision ID: ee6bc7f24531
Revises: 436c51f42eca
Create Date: 2023-05-27 18:34:25.055056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6bc7f24531'
down_revision = '436c51f42eca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
